### ISSUE TITLE
Ingénieur.e d'Affaires Junior 

### ISSUE THREAD

**Issue by louismarslen** [CoddityTeam/crew#11]
## TL;DR

🎓 peu importe / 💼 junior / 💰30-35K€ fixe + variable déplafonné

---

## Coddiquoi ?

Coddity est une société de conseil spécialisée en **développement et gestion de projets web et data** fondée en 2016 par Matthieu et Christopher, respectivement ex-directeur d’agence et responsable de BU chez un acteur majeur de l’industrie des services numériques.

Nous sommes 30 et nous intervenons directement chez nos clients (start-ups, PMEs et labs d’innovation de grands groupes) sur des missions de développement web, d’infrastructure et de gestion de projets agile.

**On aime la tech, le travail bien fait et la convivialité**. C’est pourquoi nous investissons beaucoup pour maintenir et développer une ambiance de partage dans un environnement sain composé de personnes passionnées qui souhaitent apprendre et partager (et prendre l’apéro).

Par contre, gros point noir : nous ne sommes pas lauréat GreatPlaceToWork, déso 😕

---

## Contexte

**Notre organisation est horizontale**, en lien direct avec les co-fondateurs. L’équipe est composée de 20 consultant.e.s et du pôle de gestion composé des deux fondateurs - Matthieu et Christopher, de Louis - en charge du développement commercial et marketing, de Rosy - notre responsable des opérations.

Nous avons l’ambition de **doubler nos effectifs à horizon 3 ans**, jusqu’à une cinquantaine de consultant.e.s, tout en développant de nouveaux clients et en asseyant notre présence chez nos clients actuels.

---

## Mission

Nous avons besoin de renforcer nos forces commerciales pour atteindre nos objectifs de croissance. C’est dans ce cadre que nous recherchons un.e **Ingénieur.e d’affaires junior** pour apporter du sang neuf et nous aider à implémenter notre stratégie commerciale.

Votre mission, si vous l’acceptez, sera de faire décoller le business chez Coddity, en travaillant main dans la main avec Louis, ainsi qu’avec Matthieu et Christopher. Concrètement :

- Vous serez en charge de **partir à la chasse aux nouveaux clients** avec Louis :
    - Concevoir et implémenter des stratégies de prospection intelligentes : ciblage précis, multicanal (call, mail, LinkedIn mais aussi d’autres canaux secrets 🤫 ), automatisation ;
    - Présenter les offres de Coddity lors de rendez-vous avec des potentiels clients (managers d’équipe technique, directeur.rice d’entité, CTO, DSI etc.) ;
    - Faire du “lead nurtering” pour maintenir le contact et développer les relations avec les prospects qualifiés.
- **Vous prendrez soin de nos clients** pour renforcer notre collaboration avec eux.
- Vous vous occuperez de **faire matcher les besoins de nos clients avec nos consultant.e.s** disponibles :
    - Recueillir et affiner les besoins de nos clients pour être sûr d’y répondre au mieux ;
    - S’assurer de la bonne préparation des consultant.e.s aux soutenances clients ;
    - Animer les rencontres entre les consultant.e.s Coddity et les clients ;
    - Négocier et “closer” des contrats.
- Vous vous assurerez que les missions de nos consultant.e.s se déroulent au mieux :
    - Assurer le suivi opérationnel des missions avec les consultant.e.s et les clients.

Nous rejoindre à cette étape de développement c’est la chance de **participer à la mise en place d’une stratégie de forte croissance**, d’acquérir très vite une autonomie forte, de se permettre de **tester de nouvelles idées** en étant challengé par Louis, Christopher et Matthieu. Vous aurez aussi l’occasion de **monter en compétence sur les pratiques Sales à l’état de l’art** (Growth, Sales Automation).

---

## Profil

- **Pas de parcours académique spécifique** : peu importe que vous sortiez d’une grande école, d’une école d’info ou que vous ayez un master STAPS ou un BEP Cuisine ;
- En revanche :
    - Vous aimez le **challenge** et vous n’avez pas peur de partir au combat ;
    - Vous vous intéressez aux autres, vous aimez discuter et vous vous exprimez bien à l’écrit comment à l’oral ;
    - Vous avez un intérêt / une curiosité pour le monde de la tech.
    

---

## Pratique

Ce poste est ouvert en **CDI**, pour un démarrage immédiat ou à 3 mois. 

Nos bureaux sont situés dans le 11ème à Paris, à côté de Faidherbe / Nation. Nous incluons **un jour de télétravail par semaine**.

**Package (le argent) :**

- Base fixe entre 30 et 35k€
- Variable déplafonné indéxé sur le chiffre d’affaires généré

**Aussi** : 

- Mutuelle Alan
- Tickets restaurants à 8,50€
- Carte Navigo prise en charge à 50%
- Environ 1 journée par mois libérée de contraintes clients / business pour se former

---

## On se rencontre ?

Ça se passe ici : [louis@coddity.com](mailto:louis@coddity.com)

Nous avons hâte d’échanger avec vous ! 🤘

---

## Ressources

- Notre site web (une nouvelle version est en construction) : [coddity.com](http://www.coddity.com)
- Notre blog tout neuf : [blog.coddity.com](http://blog.coddity.com)
- Notre LinkedIn pour s’imprégner de notre image : [Page LinkedIn Coddity](https://www.linkedin.com/company/coddity)
- Notre side-project préféré : [MOVAI CODE](https://github.com/CoddityTeam/movaicode)

**Comment by Matthieu-Coddity** [comment]
trouvé !
