### ISSUE TITLE
ca marche po

### ISSUE THREAD

**Issue by aymerickmichelet** [CoddityTeam/crew#20]
Bien le bonjour !

Je suis uniquement de passage pour vous indiquer que https://www.coddity.com ne fonctionne pas. Apparemment, Ngnix ne le redirige pas correctement sur https://coddity.com ^^. Preuve à l'appui 😱
![image](https://user-images.githubusercontent.com/32719398/204171650-a3aa570b-8c86-477c-a603-84181641b2e1.png)

Sur ce, ce fut un plaisir 🫡

PS: j'aime bien le mood de votre organisation 😁

**Comment by pitininja** [comment]
Salut @aymerickmichelet

Merci pour le signalement, le problème a été résolu et la personne responsable a été licenciée

Nous aussi nous aimons le mood de notre organisation
