### ISSUE TITLE
Développeur / Développeuse backend Python

### ISSUE THREAD

**Issue by louismarslen** [CoddityTeam/crew#4]
**>>> git status**
Coddity est une ESN un peu punk de 30 personnes spécialisée en développement logiciel et data science.

**>>> git checkout coddity-clients**
Nos clients sont majoritairement des anciennes startups, des labs d’innovation de grands groupes et des éditeurs de logiciels spécialisés.

**>>> git checkout coddity-core**
Nous aimons la tech et souhaitons rester une entreprise à taille humaine en recrutant des personnes curieuses, bienveillantes et passionnées. Nous sommes persuadés que c’est comme cela que nous pourrons maintenir et renforcer une équipe qui aime le partage et dans laquelle chacun apprend des autres et progresse dans le sens qu’elle souhaite.

**>>> git checkout other-activities**
Depuis plus d’un an, Coddity édite trois logiciels en complément de ses activités de service : Hubot - plateforme de datavisualisation de performance et de conversations de chatbot, Freeday - plateforme web et bot Slack intelligent pour la gestion des congés - et Confusioner - outil de mesure et d’amélioration des performances d'agents NLU déployés sur DialogFlow.

**>>> git show --notes --pretty job-details**
Nous recherchons un développeur ou une développeuse backend Python ayant au moins 3 ans d’expérience pour nous rejoindre. Nous recrutons des personnes pour ce qu’elles sont et ce qu’elles peuvent devenir, pas pour une mission spécifique.

**>>> git show --notes --pretty potential-missions**
Toutefois, voici deux exemples de mission que vous pourrez rejoindre en tant développeur backend Python chez Coddity : rejoindre l'équipe d'industrialisation de modèles de Machine Learning du Lab d'innovation d'une grande banque, travailler sur le développement d'une plateforme web pour faciliter l'écriture d'algo de Data Science sur une architecture micro-services.

**>>> git show --notes savoir-faire**
Quelques pré-requis tout de même : 
- Maîtrise de Python 3
- Maîtrise de FastAPI ou Flask
- Maîtrise de Git / Git-flow
- Sensible à la qualité de code : tests, conventions de code
- Intérêt pour la conception logicielle : architecture, design patterns
- Vous avez déjà fait un peu de frontend avec React, Vue ou Svelte ? +10 points
- Vous avez déjà touché à la partie DevOps (Docker, CI/CD..) ? +10 points
- Les deux ? JUSTE TAKE MY MONEY !

**>>> git show --notes savoir-etre**
Curiosité, humilité, bienveillance et passion. Idéalement, vous êtes un peu fou.

**>>> git config --global coddity.localisation**
Nos bureaux sont situés rue de Montreuil dans le 11ème et à Saint Léonard de Noblat en Haute-Vienne (télétravail is complètement ok). 

**>>> git commit -m “feature/a-brave-new-world: added candidature + why not rencontrer you”**

**>>> git push --force origin candidature louis.marslen@coddity.com (ou par MP LinkedIn)**

**Comment by mankarali** [comment]
Bonjour Luis,

Je m'intéresse ce poste - Développeur Python - 

Bien cordialement 
Mustafa 
https://github.com/mankarali
